### ISSUE TITLE
FX (US)

### ISSUE THREAD

**Issue by Supremicus** [Prinz23/sb_network_timezones#4]
Hey prinz, could you add FX (US) some time.

**Comment by Prinz23** [comment]
https://github.com/Prinz23/sb_network_timezones/commit/ab7293021f5bcdcfce873790604e80bd647454f2

**Comment by Supremicus** [comment]
I'll just add to this one mate, looks like they just changed TNT to TNT (US) aswell.

**Comment by Prinz23** [comment]
https://github.com/Prinz23/sb_network_timezones/commit/8c3807ff5562949a7049891f8dc47bcea8839574
