### ISSUE TITLE
TVN vs tvN

### ISSUE THREAD

**Issue by markus101** [Prinz23/sb_network_timezones#8]
It looks like there are two TVN networks in use on TheTVDB one being the entry listed here: https://github.com/Prinz23/sb_network_timezones/blob/c4349dcc9662fddb2954d6cc88287a0ae8b839e3/network_timezones.txt#L2108

and the other being a Korean channel, listed as `tvN`. Should `tvN` be added as another channel or is a difference in case a problem? (A difference in case only will be a small problem for my use, but that can be overcome if it's acceptable).

`tvN` should have the timezone `Asia/Seoul`.

Example show on tvN: https://www.thetvdb.com/series/342909

**Comment by Prinz23** [comment]
tvN is already listed as an extra network:

https://github.com/Prinz23/sb_network_timezones/blob/master/network_timezones.txt#L2620

**Comment by markus101** [comment]
Ahh, sorry I missed that when parsing the list. Looks like the issue is on our end. Thanks!
